development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: 127.0.0.1
  database: inquirly_14_th_jul 
  #database: inquirly_v2_development
  #database: inquirly_apr_release
  pool: 5
  username: postgres
  password: postgres
  # socket: /var/run/mysqld/mysqld.sock


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: 127.0.0.1
  database: inquirly_13thNov_release
  pool: 5
  username: postgres
  password: root
  # socket: /var/run/mysqld/mysqld.sock

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: <%= ENV['RDBMS_HOST'] %>
  database: <%= ENV['RDBMS_DB'] %>
  pool: <%= ENV['RDBMS_POOL'] %>
  username: <%= ENV['RDBMS_USERNAME'] %>
  password: <%= ENV['RDBMS_PASSWORD'] %>
    # socket: /var/run/mysqld/mysqld.sock
