# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daac9090db05375ed1f816769ab46ad8cbff5be7562cc8d39984746bbd558e9ef2c5562353a235a2d1e6d627e7c21eac89ff7d54785b6d524e1edd6018fb2598

test:
  secret_key_base: 057ae9723de8328e74162483d9f19d3c07664f5cb8dbf3bf1b616179d7aef15ab1d51ef7432cff3a1b133feec7ea61b7c817b1f6b3581d1319a3e45fa533b4f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
